/*
 * JS for Account generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'd4849e18-8700-4ed2-b6e2-0496353af5f1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Nov30",
    "location": "Nov30.html"
}, {
    "name": "Dec3",
    "location": "Dec3.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Products",
    "location": "Products.html"
}];

function Account_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Account_mobilenavbar_6',
        'home_item': 'Account_home_item',
        'products_item': 'Account_products_item',
        'account_item': 'Account_account_item',
        'nov30': 'Account_nov30',
        'mobilenavbaritem_16': 'Account_mobilenavbaritem_16',
        'mobileworkarea_10': 'Account_mobileworkarea_10',
        'mobileworkarea_10_24_25': 'Account_mobileworkarea_10_24_25',
        'mobilecollapsblock_14_25_26': 'Account_mobilecollapsblock_14_25_26',
        'mobilecollapsblockheader_15_26_27': 'Account_mobilecollapsblockheader_15_26_27',
        'mobilecollapsblockcontent_16_27_28': 'Account_mobilecollapsblockcontent_16_27_28',
        'mobilecollapsblock_34_45_59_60': 'Account_mobilecollapsblock_34_45_59_60',
        'mobilecollapsblockheader_35_46_60_61': 'Account_mobilecollapsblockheader_35_46_60_61',
        'mobilecollapsblockcontent_36_47_61_62': 'Account_mobilecollapsblockcontent_36_47_61_62',
        'mobilegrid_37_48_62_63': 'Account_mobilegrid_37_48_62_63',
        'mobilegridcell_38_49_63_64': 'Account_mobilegridcell_38_49_63_64',
        'mobilelabel_42_50_64_65': 'Account_mobilelabel_42_50_64_65',
        'mobilegridcell_39_51_65_66': 'Account_mobilegridcell_39_51_65_66',
        'mobilelabel_55_66_67': 'Account_mobilelabel_55_66_67',
        'mobilegridcell_40_52_67_68': 'Account_mobilegridcell_40_52_67_68',
        'mobilelabel_43_53_68_69': 'Account_mobilelabel_43_53_68_69',
        'mobilegridcell_41_54_69_70': 'Account_mobilegridcell_41_54_69_70',
        'mobilelabel_56_70_71': 'Account_mobilelabel_56_70_71',
        'mobilecollapsblock_34_45_72_73': 'Account_mobilecollapsblock_34_45_72_73',
        'mobilecollapsblockheader_35_46_73_74': 'Account_mobilecollapsblockheader_35_46_73_74',
        'mobilecollapsblockcontent_36_47_74_75': 'Account_mobilecollapsblockcontent_36_47_74_75',
        'mobilegrid_37_48_75_76': 'Account_mobilegrid_37_48_75_76',
        'mobilegridcell_38_49_76_77': 'Account_mobilegridcell_38_49_76_77',
        'mobilelabel_42_50_77_78': 'Account_mobilelabel_42_50_77_78',
        'mobilegridcell_39_51_78_79': 'Account_mobilegridcell_39_51_78_79',
        'mobilelabel_55_79_80': 'Account_mobilelabel_55_79_80',
        'mobilegridcell_40_52_80_81': 'Account_mobilegridcell_40_52_80_81',
        'mobilelabel_43_53_81_82': 'Account_mobilelabel_43_53_81_82',
        'mobilegridcell_41_54_82_83': 'Account_mobilegridcell_41_54_82_83',
        'mobilelabel_56_83_84': 'Account_mobilelabel_56_83_84',
        'mobilecollapsblock_34_45_85_86': 'Account_mobilecollapsblock_34_45_85_86',
        'mobilecollapsblockheader_35_46_86_87': 'Account_mobilecollapsblockheader_35_46_86_87',
        'mobilecollapsblockcontent_36_47_87_88': 'Account_mobilecollapsblockcontent_36_47_87_88',
        'mobilegrid_37_48_88_89': 'Account_mobilegrid_37_48_88_89',
        'mobilegridcell_38_49_89_90': 'Account_mobilegridcell_38_49_89_90',
        'mobilelabel_42_50_90_91': 'Account_mobilelabel_42_50_90_91',
        'mobilegridcell_39_51_91_92': 'Account_mobilegridcell_39_51_91_92',
        'mobilelabel_55_92_93': 'Account_mobilelabel_55_92_93',
        'mobilegridcell_40_52_93_94': 'Account_mobilegridcell_40_52_93_94',
        'mobilelabel_43_53_94_95': 'Account_mobilelabel_43_53_94_95',
        'mobilegridcell_41_54_95_96': 'Account_mobilegridcell_41_54_95_96',
        'mobilelabel_56_96_97': 'Account_mobilelabel_56_96_97',
        'mobilecollapsblock_34_45_111_112': 'Account_mobilecollapsblock_34_45_111_112',
        'mobilecollapsblockheader_35_46_112_113': 'Account_mobilecollapsblockheader_35_46_112_113',
        'mobilecollapsblockcontent_36_47_113_114': 'Account_mobilecollapsblockcontent_36_47_113_114'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Account';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Account_onLoad = function() {
        Account_elementsExtraJS();
        Account_deviceEvents();
        Account_windowEvents();
        Account_elementsEvents();
    };
    // screen window events
    function Account_windowEvents() {
        $('#Account').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Account_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Account_elementsExtraJS() {
        // screen (Account) extra code
        /* mobilecollapsblock_14_25_26 */
        $("#Account_mobilecollapsblock_14_25_26 .ui-collapsible-heading-toggle").attr("tabindex", "1");
        /* mobilecollapsblock_34_45_59_60 */
        $("#Account_mobilecollapsblock_34_45_59_60 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_72_73 */
        $("#Account_mobilecollapsblock_34_45_72_73 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_85_86 */
        $("#Account_mobilecollapsblock_34_45_85_86 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_111_112 */
        $("#Account_mobilecollapsblock_34_45_111_112 .ui-collapsible-heading-toggle").attr("tabindex", "4");
    };
    // screen elements handler
    function Account_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Account_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        }, '#Account_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Account_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });
                }
            },
        }, '#Account_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Account_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Account', {
                        reverse: false
                    });
                }
            },
        }, '#Account_mobileheader1 [name="account_item"]');
        $(document).off("click", '#Account_mobileheader1 [name="nov30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Nov30', {
                        reverse: false
                    });
                }
            },
        }, '#Account_mobileheader1 [name="nov30"]');
        $(document).off("click", '#Account_mobileheader1 [name="mobilenavbaritem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Dec3', {
                        reverse: false
                    });
                }
            },
        }, '#Account_mobileheader1 [name="mobilenavbaritem_16"]');
    };
    $(document).off("pagebeforeshow", "#Account").on("pagebeforeshow", "#Account", function(event, ui) {
        Apperyio.CurrentScreen = "Account";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Account_onLoad();
};
$(document).off("pagecreate", "#Account").on("pagecreate", "#Account", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Account_js();
});