/*
 * JS for Nov30 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'd4849e18-8700-4ed2-b6e2-0496353af5f1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Nov30",
    "location": "Nov30.html"
}, {
    "name": "Dec3",
    "location": "Dec3.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Products",
    "location": "Products.html"
}];

function Nov30_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Nov30_mobilenavbar_6',
        'home_item': 'Nov30_home_item',
        'products_item': 'Nov30_products_item',
        'account_item': 'Nov30_account_item',
        'nov30': 'Nov30_nov30',
        'mobilenavbaritem_16': 'Nov30_mobilenavbaritem_16',
        'mobileworkarea_10_24_32': 'Nov30_mobileworkarea_10_24_32',
        'mobilecollapsblock_14_25_33': 'Nov30_mobilecollapsblock_14_25_33',
        'mobilecollapsblockheader_15_26_34': 'Nov30_mobilecollapsblockheader_15_26_34',
        'mobilecollapsblockcontent_16_27_35': 'Nov30_mobilecollapsblockcontent_16_27_35',
        'mobilecollapsblock_34_45_59_60': 'Nov30_mobilecollapsblock_34_45_59_60',
        'mobilecollapsblockheader_35_46_60_61': 'Nov30_mobilecollapsblockheader_35_46_60_61',
        'mobilecollapsblockcontent_36_47_61_62': 'Nov30_mobilecollapsblockcontent_36_47_61_62',
        'mobilegrid_37_48_62_63': 'Nov30_mobilegrid_37_48_62_63',
        'mobilegridcell_38_49_63_64': 'Nov30_mobilegridcell_38_49_63_64',
        'mobilelabel_42_50_64_65': 'Nov30_mobilelabel_42_50_64_65',
        'mobilegridcell_39_51_65_66': 'Nov30_mobilegridcell_39_51_65_66',
        'mobilelabel_55_66_67': 'Nov30_mobilelabel_55_66_67',
        'mobilegridcell_40_52_67_68': 'Nov30_mobilegridcell_40_52_67_68',
        'mobilelabel_43_53_68_69': 'Nov30_mobilelabel_43_53_68_69',
        'mobilegridcell_41_54_69_70': 'Nov30_mobilegridcell_41_54_69_70',
        'mobilelabel_56_70_71': 'Nov30_mobilelabel_56_70_71',
        'mobilecollapsblock_34_45_72_73': 'Nov30_mobilecollapsblock_34_45_72_73',
        'mobilecollapsblockheader_35_46_73_74': 'Nov30_mobilecollapsblockheader_35_46_73_74',
        'mobilecollapsblockcontent_36_47_74_75': 'Nov30_mobilecollapsblockcontent_36_47_74_75',
        'mobilegrid_37_48_75_76': 'Nov30_mobilegrid_37_48_75_76',
        'mobilegridcell_38_49_76_77': 'Nov30_mobilegridcell_38_49_76_77',
        'mobilelabel_42_50_77_78': 'Nov30_mobilelabel_42_50_77_78',
        'mobilegridcell_39_51_78_79': 'Nov30_mobilegridcell_39_51_78_79',
        'mobilelabel_55_79_80': 'Nov30_mobilelabel_55_79_80',
        'mobilegridcell_40_52_80_81': 'Nov30_mobilegridcell_40_52_80_81',
        'mobilelabel_43_53_81_82': 'Nov30_mobilelabel_43_53_81_82',
        'mobilegridcell_41_54_82_83': 'Nov30_mobilegridcell_41_54_82_83',
        'mobilelabel_56_83_84': 'Nov30_mobilelabel_56_83_84',
        'mobilecollapsblock_34_45_85_86': 'Nov30_mobilecollapsblock_34_45_85_86',
        'mobilecollapsblockheader_35_46_86_87': 'Nov30_mobilecollapsblockheader_35_46_86_87',
        'mobilecollapsblockcontent_36_47_87_88': 'Nov30_mobilecollapsblockcontent_36_47_87_88',
        'mobilegrid_37_48_88_89': 'Nov30_mobilegrid_37_48_88_89',
        'mobilegridcell_38_49_89_90': 'Nov30_mobilegridcell_38_49_89_90',
        'mobilelabel_42_50_90_91': 'Nov30_mobilelabel_42_50_90_91',
        'mobilegridcell_39_51_91_92': 'Nov30_mobilegridcell_39_51_91_92',
        'mobilelabel_55_92_93': 'Nov30_mobilelabel_55_92_93',
        'mobilegridcell_40_52_93_94': 'Nov30_mobilegridcell_40_52_93_94',
        'mobilelabel_43_53_94_95': 'Nov30_mobilelabel_43_53_94_95',
        'mobilegridcell_41_54_95_96': 'Nov30_mobilegridcell_41_54_95_96',
        'mobilelabel_56_96_97': 'Nov30_mobilelabel_56_96_97',
        'mobilecollapsblock_34_45_217': 'Nov30_mobilecollapsblock_34_45_217',
        'mobilecollapsblockheader_35_46_218': 'Nov30_mobilecollapsblockheader_35_46_218',
        'mobilecollapsblockcontent_36_47_219': 'Nov30_mobilecollapsblockcontent_36_47_219',
        'mobilegrid_37_48_220': 'Nov30_mobilegrid_37_48_220',
        'mobilegridcell_38_49_221': 'Nov30_mobilegridcell_38_49_221',
        'mobilelabel_42_50_222': 'Nov30_mobilelabel_42_50_222',
        'mobilegridcell_39_51_223': 'Nov30_mobilegridcell_39_51_223',
        'mobilelabel_55_224': 'Nov30_mobilelabel_55_224',
        'mobilegridcell_40_52_225': 'Nov30_mobilegridcell_40_52_225',
        'mobilelabel_43_53_226': 'Nov30_mobilelabel_43_53_226',
        'mobilegridcell_41_54_227': 'Nov30_mobilegridcell_41_54_227',
        'mobilelabel_56_228': 'Nov30_mobilelabel_56_228',
        'mobilecollapsblock_34_45_111_112': 'Nov30_mobilecollapsblock_34_45_111_112',
        'mobilecollapsblockheader_35_46_112_113': 'Nov30_mobilecollapsblockheader_35_46_112_113',
        'mobilecollapsblockcontent_36_47_113_114': 'Nov30_mobilecollapsblockcontent_36_47_113_114',
        'mobilecollapsblock_17_28_137': 'Nov30_mobilecollapsblock_17_28_137',
        'mobilecollapsblockheader_18_29_138': 'Nov30_mobilecollapsblockheader_18_29_138',
        'mobilecollapsblockcontent_19_30_139': 'Nov30_mobilecollapsblockcontent_19_30_139',
        'mobilecollapsblock_34_45_137_140': 'Nov30_mobilecollapsblock_34_45_137_140',
        'mobilecollapsblockheader_35_46_138_141': 'Nov30_mobilecollapsblockheader_35_46_138_141',
        'mobilecollapsblockcontent_36_47_139_142': 'Nov30_mobilecollapsblockcontent_36_47_139_142',
        'mobilegrid_37_48_140_143': 'Nov30_mobilegrid_37_48_140_143',
        'mobilegridcell_38_49_141_144': 'Nov30_mobilegridcell_38_49_141_144',
        'mobilelabel_42_50_142_145': 'Nov30_mobilelabel_42_50_142_145',
        'mobilegridcell_39_51_143_146': 'Nov30_mobilegridcell_39_51_143_146',
        'mobilelabel_55_144_147': 'Nov30_mobilelabel_55_144_147',
        'mobilegridcell_40_52_145_148': 'Nov30_mobilegridcell_40_52_145_148',
        'mobilelabel_43_53_146_149': 'Nov30_mobilelabel_43_53_146_149',
        'mobilegridcell_41_54_147_150': 'Nov30_mobilegridcell_41_54_147_150',
        'mobilelabel_56_148_151': 'Nov30_mobilelabel_56_148_151',
        'mobilecollapsblock_34_45_163_164': 'Nov30_mobilecollapsblock_34_45_163_164',
        'mobilecollapsblockheader_35_46_164_165': 'Nov30_mobilecollapsblockheader_35_46_164_165',
        'mobilecollapsblockcontent_36_47_165_166': 'Nov30_mobilecollapsblockcontent_36_47_165_166',
        'mobilecollapsblock_34_45_176_177': 'Nov30_mobilecollapsblock_34_45_176_177',
        'mobilecollapsblockheader_35_46_177_178': 'Nov30_mobilecollapsblockheader_35_46_177_178',
        'mobilecollapsblockcontent_36_47_178_179': 'Nov30_mobilecollapsblockcontent_36_47_178_179',
        'mobilegrid_37_48_179_180': 'Nov30_mobilegrid_37_48_179_180',
        'mobilegridcell_38_49_180_181': 'Nov30_mobilegridcell_38_49_180_181',
        'mobilelabel_42_50_181_182': 'Nov30_mobilelabel_42_50_181_182',
        'mobilegridcell_39_51_182_183': 'Nov30_mobilegridcell_39_51_182_183',
        'mobilelabel_55_183_184': 'Nov30_mobilelabel_55_183_184',
        'mobilegridcell_40_52_184_185': 'Nov30_mobilegridcell_40_52_184_185',
        'mobilelabel_43_53_185_186': 'Nov30_mobilelabel_43_53_185_186',
        'mobilegridcell_41_54_186_187': 'Nov30_mobilegridcell_41_54_186_187',
        'mobilelabel_56_187_188': 'Nov30_mobilelabel_56_187_188',
        'mobilecollapsblock_34_45_230': 'Nov30_mobilecollapsblock_34_45_230',
        'mobilecollapsblockheader_35_46_231': 'Nov30_mobilecollapsblockheader_35_46_231',
        'mobilecollapsblockcontent_36_47_232': 'Nov30_mobilecollapsblockcontent_36_47_232',
        'mobilegrid_37_48_233': 'Nov30_mobilegrid_37_48_233',
        'mobilegridcell_38_49_234': 'Nov30_mobilegridcell_38_49_234',
        'mobilelabel_42_50_235': 'Nov30_mobilelabel_42_50_235',
        'mobilegridcell_39_51_236': 'Nov30_mobilegridcell_39_51_236',
        'mobilelabel_55_237': 'Nov30_mobilelabel_55_237',
        'mobilegridcell_40_52_238': 'Nov30_mobilegridcell_40_52_238',
        'mobilelabel_43_53_239': 'Nov30_mobilelabel_43_53_239',
        'mobilegridcell_41_54_240': 'Nov30_mobilegridcell_41_54_240',
        'mobilelabel_56_241': 'Nov30_mobilelabel_56_241',
        'mobilecollapsblock_20_31_189': 'Nov30_mobilecollapsblock_20_31_189',
        'mobilecollapsblockheader_21_32_190': 'Nov30_mobilecollapsblockheader_21_32_190',
        'mobilecollapsblockcontent_22_33_191': 'Nov30_mobilecollapsblockcontent_22_33_191',
        'mobilecollapsblock_34_45_189_192': 'Nov30_mobilecollapsblock_34_45_189_192',
        'mobilecollapsblockheader_35_46_190_193': 'Nov30_mobilecollapsblockheader_35_46_190_193',
        'mobilecollapsblockcontent_36_47_191_194': 'Nov30_mobilecollapsblockcontent_36_47_191_194',
        'mobilegrid_37_48_192_195': 'Nov30_mobilegrid_37_48_192_195',
        'mobilegridcell_38_49_193_196': 'Nov30_mobilegridcell_38_49_193_196',
        'mobilelabel_42_50_194_197': 'Nov30_mobilelabel_42_50_194_197',
        'mobilegridcell_39_51_195_198': 'Nov30_mobilegridcell_39_51_195_198',
        'mobilelabel_55_196_199': 'Nov30_mobilelabel_55_196_199',
        'mobilegridcell_40_52_197_200': 'Nov30_mobilegridcell_40_52_197_200',
        'mobilelabel_43_53_198_201': 'Nov30_mobilelabel_43_53_198_201',
        'mobilegridcell_41_54_199_202': 'Nov30_mobilegridcell_41_54_199_202',
        'mobilelabel_56_200_203': 'Nov30_mobilelabel_56_200_203'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Nov30';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Nov30_onLoad = function() {
        Nov30_elementsExtraJS();
        Nov30_deviceEvents();
        Nov30_windowEvents();
        Nov30_elementsEvents();
    };
    // screen window events
    function Nov30_windowEvents() {
        $('#Nov30').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Nov30_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Nov30_elementsExtraJS() {
        // screen (Nov30) extra code
        /* mobilecollapsblock_14_25_33 */
        $("#Nov30_mobilecollapsblock_14_25_33 .ui-collapsible-heading-toggle").attr("tabindex", "1");
        /* mobilecollapsblock_34_45_59_60 */
        $("#Nov30_mobilecollapsblock_34_45_59_60 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_72_73 */
        $("#Nov30_mobilecollapsblock_34_45_72_73 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_85_86 */
        $("#Nov30_mobilecollapsblock_34_45_85_86 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_217 */
        $("#Nov30_mobilecollapsblock_34_45_217 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_111_112 */
        $("#Nov30_mobilecollapsblock_34_45_111_112 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_17_28_137 */
        $("#Nov30_mobilecollapsblock_17_28_137 .ui-collapsible-heading-toggle").attr("tabindex", "2");
        /* mobilecollapsblock_34_45_137_140 */
        $("#Nov30_mobilecollapsblock_34_45_137_140 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_163_164 */
        $("#Nov30_mobilecollapsblock_34_45_163_164 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_176_177 */
        $("#Nov30_mobilecollapsblock_34_45_176_177 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_230 */
        $("#Nov30_mobilecollapsblock_34_45_230 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_20_31_189 */
        $("#Nov30_mobilecollapsblock_20_31_189 .ui-collapsible-heading-toggle").attr("tabindex", "3");
        /* mobilecollapsblock_34_45_189_192 */
        $("#Nov30_mobilecollapsblock_34_45_189_192 .ui-collapsible-heading-toggle").attr("tabindex", "4");
    };
    // screen elements handler
    function Nov30_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Nov30_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        }, '#Nov30_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Nov30_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });
                }
            },
        }, '#Nov30_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Nov30_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Account', {
                        reverse: false
                    });
                }
            },
        }, '#Nov30_mobileheader1 [name="account_item"]');
        $(document).off("click", '#Nov30_mobileheader1 [name="nov30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Nov30', {
                        reverse: false
                    });
                }
            },
        }, '#Nov30_mobileheader1 [name="nov30"]');
        $(document).off("click", '#Nov30_mobileheader1 [name="mobilenavbaritem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Dec3', {
                        reverse: false
                    });
                }
            },
        }, '#Nov30_mobileheader1 [name="mobilenavbaritem_16"]');
    };
    $(document).off("pagebeforeshow", "#Nov30").on("pagebeforeshow", "#Nov30", function(event, ui) {
        Apperyio.CurrentScreen = "Nov30";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Nov30_onLoad();
};
$(document).off("pagecreate", "#Nov30").on("pagecreate", "#Nov30", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Nov30_js();
});