/*
 * JS for Products generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return 'd4849e18-8700-4ed2-b6e2-0496353af5f1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Nov30",
    "location": "Nov30.html"
}, {
    "name": "Dec3",
    "location": "Dec3.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Products",
    "location": "Products.html"
}];

function Products_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Products_mobilenavbar_6',
        'home_item': 'Products_home_item',
        'products_item': 'Products_products_item',
        'account_item': 'Products_account_item',
        'nov30': 'Products_nov30',
        'mobilenavbaritem_16': 'Products_mobilenavbaritem_16',
        'mobileworkarea_10': 'Products_mobileworkarea_10',
        'mobileworkarea_10_24_32': 'Products_mobileworkarea_10_24_32',
        'mobilecollapsblock_14_25_33': 'Products_mobilecollapsblock_14_25_33',
        'mobilecollapsblockheader_15_26_34': 'Products_mobilecollapsblockheader_15_26_34',
        'mobilecollapsblockcontent_16_27_35': 'Products_mobilecollapsblockcontent_16_27_35',
        'mobilecollapsblock_34_45_59_60': 'Products_mobilecollapsblock_34_45_59_60',
        'mobilecollapsblockheader_35_46_60_61': 'Products_mobilecollapsblockheader_35_46_60_61',
        'mobilecollapsblockcontent_36_47_61_62': 'Products_mobilecollapsblockcontent_36_47_61_62',
        'mobilegrid_37_48_62_63': 'Products_mobilegrid_37_48_62_63',
        'mobilegridcell_38_49_63_64': 'Products_mobilegridcell_38_49_63_64',
        'mobilelabel_42_50_64_65': 'Products_mobilelabel_42_50_64_65',
        'mobilegridcell_39_51_65_66': 'Products_mobilegridcell_39_51_65_66',
        'mobilelabel_55_66_67': 'Products_mobilelabel_55_66_67',
        'mobilegridcell_40_52_67_68': 'Products_mobilegridcell_40_52_67_68',
        'mobilelabel_43_53_68_69': 'Products_mobilelabel_43_53_68_69',
        'mobilegridcell_41_54_69_70': 'Products_mobilegridcell_41_54_69_70',
        'mobilelabel_56_70_71': 'Products_mobilelabel_56_70_71',
        'mobilecollapsblock_34_45_72_73': 'Products_mobilecollapsblock_34_45_72_73',
        'mobilecollapsblockheader_35_46_73_74': 'Products_mobilecollapsblockheader_35_46_73_74',
        'mobilecollapsblockcontent_36_47_74_75': 'Products_mobilecollapsblockcontent_36_47_74_75',
        'mobilegrid_37_48_75_76': 'Products_mobilegrid_37_48_75_76',
        'mobilegridcell_38_49_76_77': 'Products_mobilegridcell_38_49_76_77',
        'mobilelabel_42_50_77_78': 'Products_mobilelabel_42_50_77_78',
        'mobilegridcell_39_51_78_79': 'Products_mobilegridcell_39_51_78_79',
        'mobilelabel_55_79_80': 'Products_mobilelabel_55_79_80',
        'mobilegridcell_40_52_80_81': 'Products_mobilegridcell_40_52_80_81',
        'mobilelabel_43_53_81_82': 'Products_mobilelabel_43_53_81_82',
        'mobilegridcell_41_54_82_83': 'Products_mobilegridcell_41_54_82_83',
        'mobilelabel_56_83_84': 'Products_mobilelabel_56_83_84',
        'mobilecollapsblock_34_45_111_112': 'Products_mobilecollapsblock_34_45_111_112',
        'mobilecollapsblockheader_35_46_112_113': 'Products_mobilecollapsblockheader_35_46_112_113',
        'mobilecollapsblockcontent_36_47_113_114': 'Products_mobilecollapsblockcontent_36_47_113_114',
        'mobilecollapsblock_34_45_85_86': 'Products_mobilecollapsblock_34_45_85_86',
        'mobilecollapsblockheader_35_46_86_87': 'Products_mobilecollapsblockheader_35_46_86_87',
        'mobilecollapsblockcontent_36_47_87_88': 'Products_mobilecollapsblockcontent_36_47_87_88',
        'mobilegrid_37_48_88_89': 'Products_mobilegrid_37_48_88_89',
        'mobilegridcell_38_49_89_90': 'Products_mobilegridcell_38_49_89_90',
        'mobilelabel_42_50_90_91': 'Products_mobilelabel_42_50_90_91',
        'mobilegridcell_39_51_91_92': 'Products_mobilegridcell_39_51_91_92',
        'mobilelabel_55_92_93': 'Products_mobilelabel_55_92_93',
        'mobilegridcell_40_52_93_94': 'Products_mobilegridcell_40_52_93_94',
        'mobilelabel_43_53_94_95': 'Products_mobilelabel_43_53_94_95',
        'mobilegridcell_41_54_95_96': 'Products_mobilegridcell_41_54_95_96',
        'mobilelabel_56_96_97': 'Products_mobilelabel_56_96_97',
        'mobilecollapsblock_17_28_137': 'Products_mobilecollapsblock_17_28_137',
        'mobilecollapsblockheader_18_29_138': 'Products_mobilecollapsblockheader_18_29_138',
        'mobilecollapsblockcontent_19_30_139': 'Products_mobilecollapsblockcontent_19_30_139',
        'mobilecollapsblock_34_45_137_140': 'Products_mobilecollapsblock_34_45_137_140',
        'mobilecollapsblockheader_35_46_138_141': 'Products_mobilecollapsblockheader_35_46_138_141',
        'mobilecollapsblockcontent_36_47_139_142': 'Products_mobilecollapsblockcontent_36_47_139_142',
        'mobilegrid_37_48_140_143': 'Products_mobilegrid_37_48_140_143',
        'mobilegridcell_38_49_141_144': 'Products_mobilegridcell_38_49_141_144',
        'mobilelabel_42_50_142_145': 'Products_mobilelabel_42_50_142_145',
        'mobilegridcell_39_51_143_146': 'Products_mobilegridcell_39_51_143_146',
        'mobilelabel_55_144_147': 'Products_mobilelabel_55_144_147',
        'mobilegridcell_40_52_145_148': 'Products_mobilegridcell_40_52_145_148',
        'mobilelabel_43_53_146_149': 'Products_mobilelabel_43_53_146_149',
        'mobilegridcell_41_54_147_150': 'Products_mobilegridcell_41_54_147_150',
        'mobilelabel_56_148_151': 'Products_mobilelabel_56_148_151',
        'mobilecollapsblock_34_45_150_152': 'Products_mobilecollapsblock_34_45_150_152',
        'mobilecollapsblockheader_35_46_151_153': 'Products_mobilecollapsblockheader_35_46_151_153',
        'mobilecollapsblockcontent_36_47_152_154': 'Products_mobilecollapsblockcontent_36_47_152_154',
        'mobilegrid_37_48_153_155': 'Products_mobilegrid_37_48_153_155',
        'mobilegridcell_38_49_154_156': 'Products_mobilegridcell_38_49_154_156',
        'mobilelabel_42_50_155_157': 'Products_mobilelabel_42_50_155_157',
        'mobilegridcell_39_51_156_158': 'Products_mobilegridcell_39_51_156_158',
        'mobilelabel_55_157_159': 'Products_mobilelabel_55_157_159',
        'mobilegridcell_40_52_158_160': 'Products_mobilegridcell_40_52_158_160',
        'mobilelabel_43_53_159_161': 'Products_mobilelabel_43_53_159_161',
        'mobilegridcell_41_54_160_162': 'Products_mobilegridcell_41_54_160_162',
        'mobilelabel_56_161_163': 'Products_mobilelabel_56_161_163',
        'mobilecollapsblock_34_45_176_177': 'Products_mobilecollapsblock_34_45_176_177',
        'mobilecollapsblockheader_35_46_177_178': 'Products_mobilecollapsblockheader_35_46_177_178',
        'mobilecollapsblockcontent_36_47_178_179': 'Products_mobilecollapsblockcontent_36_47_178_179',
        'mobilegrid_37_48_179_180': 'Products_mobilegrid_37_48_179_180',
        'mobilegridcell_38_49_180_181': 'Products_mobilegridcell_38_49_180_181',
        'mobilelabel_42_50_181_182': 'Products_mobilelabel_42_50_181_182',
        'mobilegridcell_39_51_182_183': 'Products_mobilegridcell_39_51_182_183',
        'mobilelabel_55_183_184': 'Products_mobilelabel_55_183_184',
        'mobilegridcell_40_52_184_185': 'Products_mobilegridcell_40_52_184_185',
        'mobilelabel_43_53_185_186': 'Products_mobilelabel_43_53_185_186',
        'mobilegridcell_41_54_186_187': 'Products_mobilegridcell_41_54_186_187',
        'mobilelabel_56_187_188': 'Products_mobilelabel_56_187_188',
        'mobilecollapsblock_34_45_163_164': 'Products_mobilecollapsblock_34_45_163_164',
        'mobilecollapsblockheader_35_46_164_165': 'Products_mobilecollapsblockheader_35_46_164_165',
        'mobilecollapsblockcontent_36_47_165_166': 'Products_mobilecollapsblockcontent_36_47_165_166',
        'CustomComponent1_234': 'Products_CustomComponent1_234',
        'CustomComponent1_234_mobilecollapsblock_34_217': 'Products_CustomComponent1_234_mobilecollapsblock_34_217',
        'CustomComponent1_234_mobilecollapsblockheader_35_218': 'Products_CustomComponent1_234_mobilecollapsblockheader_35_218',
        'CustomComponent1_234_mobilecollapsblockcontent_36_219': 'Products_CustomComponent1_234_mobilecollapsblockcontent_36_219',
        'CustomComponent1_234_mobilegrid_37_220': 'Products_CustomComponent1_234_mobilegrid_37_220',
        'CustomComponent1_234_mobilegridcell_38_221': 'Products_CustomComponent1_234_mobilegridcell_38_221',
        'CustomComponent1_234_mobilelabel_42_222': 'Products_CustomComponent1_234_mobilelabel_42_222',
        'CustomComponent1_234_mobilegridcell_39_223': 'Products_CustomComponent1_234_mobilegridcell_39_223',
        'CustomComponent1_234_mobilelabel_228': 'Products_CustomComponent1_234_mobilelabel_228',
        'CustomComponent1_234_mobilegridcell_40_224': 'Products_CustomComponent1_234_mobilegridcell_40_224',
        'CustomComponent1_234_mobilelabel_43_225': 'Products_CustomComponent1_234_mobilelabel_43_225',
        'CustomComponent1_234_mobilegridcell_41_226': 'Products_CustomComponent1_234_mobilegridcell_41_226',
        'CustomComponent1_234_mobilelabel_229': 'Products_CustomComponent1_234_mobilelabel_229',
        'CustomComponent1_234_mobilegridcell_230': 'Products_CustomComponent1_234_mobilegridcell_230',
        'CustomComponent1_234_mobilelabel_232': 'Products_CustomComponent1_234_mobilelabel_232',
        'CustomComponent1_234_mobilegridcell_231': 'Products_CustomComponent1_234_mobilegridcell_231',
        'CustomComponent1_234_mobilelabel_233': 'Products_CustomComponent1_234_mobilelabel_233',
        'mobilecollapsblock_34_217_236': 'Products_mobilecollapsblock_34_217_236',
        'mobilecollapsblockheader_35_218_237': 'Products_mobilecollapsblockheader_35_218_237',
        'mobilecollapsblockcontent_36_219_238': 'Products_mobilecollapsblockcontent_36_219_238',
        'mobilegrid_37_220_239': 'Products_mobilegrid_37_220_239',
        'mobilegridcell_38_221_240': 'Products_mobilegridcell_38_221_240',
        'mobilelabel_42_222_241': 'Products_mobilelabel_42_222_241',
        'mobilegridcell_39_223_242': 'Products_mobilegridcell_39_223_242',
        'mobilelabel_228_243': 'Products_mobilelabel_228_243',
        'mobilegridcell_40_224_244': 'Products_mobilegridcell_40_224_244',
        'mobilelabel_43_225_245': 'Products_mobilelabel_43_225_245',
        'mobilegridcell_41_226_246': 'Products_mobilegridcell_41_226_246',
        'mobilelabel_229_247': 'Products_mobilelabel_229_247',
        'mobilegridcell_230_248': 'Products_mobilegridcell_230_248',
        'mobilelabel_232_249': 'Products_mobilelabel_232_249',
        'mobilegridcell_231_250': 'Products_mobilegridcell_231_250',
        'mobilelabel_233_251': 'Products_mobilelabel_233_251',
        'mobilecollapsblock_20_31_189': 'Products_mobilecollapsblock_20_31_189',
        'mobilecollapsblockheader_21_32_190': 'Products_mobilecollapsblockheader_21_32_190',
        'mobilecollapsblockcontent_22_33_191': 'Products_mobilecollapsblockcontent_22_33_191',
        'mobilecollapsblock_34_45_202_204': 'Products_mobilecollapsblock_34_45_202_204',
        'mobilecollapsblockheader_35_46_203_205': 'Products_mobilecollapsblockheader_35_46_203_205',
        'mobilecollapsblockcontent_36_47_204_206': 'Products_mobilecollapsblockcontent_36_47_204_206',
        'mobilegrid_37_48_205_207': 'Products_mobilegrid_37_48_205_207',
        'mobilegridcell_38_49_206_208': 'Products_mobilegridcell_38_49_206_208',
        'mobilelabel_42_50_207_209': 'Products_mobilelabel_42_50_207_209',
        'mobilegridcell_39_51_208_210': 'Products_mobilegridcell_39_51_208_210',
        'mobilelabel_55_209_211': 'Products_mobilelabel_55_209_211',
        'mobilegridcell_40_52_210_212': 'Products_mobilegridcell_40_52_210_212',
        'mobilelabel_43_53_211_213': 'Products_mobilelabel_43_53_211_213',
        'mobilegridcell_41_54_212_214': 'Products_mobilegridcell_41_54_212_214',
        'mobilelabel_56_213_215': 'Products_mobilelabel_56_213_215'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Products';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Products_onLoad = function() {
        Products_elementsExtraJS();
        Products_deviceEvents();
        Products_windowEvents();
        Products_elementsEvents();
    };
    // screen window events
    function Products_windowEvents() {
        $('#Products').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Products_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Products_elementsExtraJS() {
        // screen (Products) extra code
        /* mobilecollapsblock_14_25_33 */
        $("#Products_mobilecollapsblock_14_25_33 .ui-collapsible-heading-toggle").attr("tabindex", "1");
        /* mobilecollapsblock_34_45_59_60 */
        $("#Products_mobilecollapsblock_34_45_59_60 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_72_73 */
        $("#Products_mobilecollapsblock_34_45_72_73 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_111_112 */
        $("#Products_mobilecollapsblock_34_45_111_112 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_85_86 */
        $("#Products_mobilecollapsblock_34_45_85_86 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_17_28_137 */
        $("#Products_mobilecollapsblock_17_28_137 .ui-collapsible-heading-toggle").attr("tabindex", "2");
        /* mobilecollapsblock_34_45_137_140 */
        $("#Products_mobilecollapsblock_34_45_137_140 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_150_152 */
        $("#Products_mobilecollapsblock_34_45_150_152 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_176_177 */
        $("#Products_mobilecollapsblock_34_45_176_177 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_45_163_164 */
        $("#Products_mobilecollapsblock_34_45_163_164 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* CustomComponent1_234_mobilecollapsblock_34_217 */
        $("#Products_CustomComponent1_234_mobilecollapsblock_34_217 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_34_217_236 */
        $("#Products_mobilecollapsblock_34_217_236 .ui-collapsible-heading-toggle").attr("tabindex", "4");
        /* mobilecollapsblock_20_31_189 */
        $("#Products_mobilecollapsblock_20_31_189 .ui-collapsible-heading-toggle").attr("tabindex", "3");
        /* mobilecollapsblock_34_45_202_204 */
        $("#Products_mobilecollapsblock_34_45_202_204 .ui-collapsible-heading-toggle").attr("tabindex", "4");
    };
    // screen elements handler
    function Products_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#Products_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        }, '#Products_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Products_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Products', {
                        reverse: false
                    });
                }
            },
        }, '#Products_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Products_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Account', {
                        reverse: false
                    });
                }
            },
        }, '#Products_mobileheader1 [name="account_item"]');
        $(document).off("click", '#Products_mobileheader1 [name="nov30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Nov30', {
                        reverse: false
                    });
                }
            },
        }, '#Products_mobileheader1 [name="nov30"]');
        $(document).off("click", '#Products_mobileheader1 [name="mobilenavbaritem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Dec3', {
                        reverse: false
                    });
                }
            },
        }, '#Products_mobileheader1 [name="mobilenavbaritem_16"]');
    };
    $(document).off("pagebeforeshow", "#Products").on("pagebeforeshow", "#Products", function(event, ui) {
        Apperyio.CurrentScreen = "Products";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Products_onLoad();
};
$(document).off("pagecreate", "#Products").on("pagecreate", "#Products", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Products_js();
});